version: '3.8'

services:
  db:
    image: 'postgres:alpine'
    env_file:
      - db.env
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - alectrion-equipment-network

  equip_api:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - alectrion-equipment-network
      - alectrion-network
    ports:
      - 4002:4002
    command: sh -c "yarn && yarn migration:run && yarn dev"

networks:
  alectrion-equipment-network:
  alectrion-network:
    external: true
